// demo/angular/src/app/app.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { CommonModule } from '@angular/common';
import { GetProductsComponent } from './components/get-products/get-products.component';
import { HeaderComponent } from './components/header/header.component';
import { EcComponent } from './modules/ec/ec.component';
import { OtecComponent } from './modules/otec/otec.component';
import { RsaComponent } from './modules/rsa/rsa.component';
import { ProductService } from './services/product.service';
import { Product } from './interfaces/service.interface';

@Component({
  selector: 'app-root',
  imports: [
    RouterOutlet,
    CommonModule,
    HeaderComponent,
    GetProductsComponent,
    EcComponent,
    OtecComponent,
    RsaComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent implements OnInit {
  private productService = inject(ProductService);

  selectedAlgorithm: string = 'EC';
  products: Product[] = [];

  async ngOnInit() {
    const result = await this.productService.getProducts();
    this.products = result.data;
  }

  handleAlgorithmChange(algorithm: string) {
    this.selectedAlgorithm = algorithm;
  }

  handleProducts(product: Product) {
    this.products = [...this.products, product];
  }
}

// examples/reactjs/src/App.tsx
import React from 'react';
import GetProducts from './components/getProducts/getProducts';
import { Header } from './components/header/header';
import { useGetProducts } from './hooks/useGetProducts';
import { EC } from './modules/ec/ec';
import { OTEC } from './modules/otec/otec';
import { RSA } from './modules/rsa/rsa';

function App() {
  const [selectedAlgorithm, setSelectedAlgorithm] =
    React.useState<string>('EC');
  const { products, handleProducts } = useGetProducts();

  const handleAlgorithmChange = (algorithm: string) => {
    setSelectedAlgorithm(algorithm);
  };

  return (
    <>
      <Header handleAlgorithmChange={handleAlgorithmChange} />
      <h2>Lista de productos:</h2>
      <GetProducts products={products} />
      <br />
      {selectedAlgorithm === 'EC' && <EC handleProducts={handleProducts} />}
      {selectedAlgorithm === 'OTEC' && <OTEC handleProducts={handleProducts} />}
      {selectedAlgorithm === 'RSA' && <RSA handleProducts={handleProducts} />}
    </>
  );
}

export default App;
